spring:
  datasource:
    url: jdbc:h2:file:/data/transaction
    username: ${DB_USER}
    password: ${DB_PASS}
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true